discord:
  - webhook: https://discord.com/api/webhooks/<your_id>/<your_token>
    widgets:
      - tradingview_advanced_chart
      - tradingview_technical_analysis
    symbols:
      - NASDAQ:MSFT
      - NASDAQ:NVDA
      - SSE_DLY:000001
      - BINANCE:BTCUSD
      - NASDAQ:NDX
      - AMEX:KWEB
