discord:
  - webhook: https://discord.com/api/webhooks/<your_id>/<your_token>
    name: Default Discord
    widgets:
      - tradingview_advanced_chart
      - tradingview_technical_analysis
    symbols:
      - NASDAQ:MSFT
      - NASDAQ:NVDA
      - SSE_DLY:000001
      - BINANCE:BTCUSD
      - NASDAQ:NDX
      - AMEX:KWEB
    # Consider using single line crontab syntax for each schedule for simplicity
    # Syntax can be found at: https://apscheduler.readthedocs.io/en/3.x/modules/triggers/cron.html?highlight=decorator
    schedules:
      - trigger: cron
        day: "*"
        hour: "08"
      - trigger: cron
        day: "*"
        hour: "16"
